// src/client/components/header/header.tsx
import "./header.css";

import { Burger, Flex } from "@mantine/core";
import { observer } from "mobx-react-lite";

import { MenuButton } from "@/components/menu-button";
import { MenuDropdown } from "@/components/menu-dropdown";

import { HeaderManager } from "./header.service";
import { EntrySearchField } from "../shared/entry-search-field";

interface HeaderProps {
    service: HeaderManager;
}

function renderHeader({ service }: HeaderProps) {
    return (
        <Flex
            className="header"
            gap={0}
            justify="flex-start"
            align="center"
            direction="row"
            wrap="nowrap"
        >
            <Burger
                opened={service.fetchLeftBarStatus.produce()}
                onClick={() => service.onToggleLeftBar.produce()}
                hiddenFrom="sm"
                size="sm"
                pr="8"
            />
            <MenuButton
                label="Home"
                onClick={() => service.onOpenHome.produce()}
            />
            <MenuDropdown
                label="File"
                data={service.fileMenuData}
                portalProps={{
                    target: service.fetchPortalSelector.produce(),
                }}
            />
            <div className="grow" />
            <EntrySearchField service={service.entrySearch} />
        </Flex>
    );
}
export const Header = observer(renderHeader);

// src/ui/header/header.svelte
<script lang="ts">
    import { Button } from "@/lib/components/button";
    import { MenuBarDropdown } from "@/lib/components/menubar-dropdown";

    import { EntrySearchField } from "../shared/entry-search";
    import type { HeaderProps } from "./header-interface";
    
    const { service }: HeaderProps = $props();
</script>

<div class="flex items-center w-full h-(--header-height) gap-0 px-3 bg-neutral-700">
    <Button
        class="h-8"
        variant="ghost"
        size="sm"
        onclick={() => service.onOpenHome.produce()}
    >
        Home
    </Button>

    <MenuBarDropdown
        label="File"
        items={service.fileMenuData}
        buttonProps={{ class: "h-8", variant: "ghost" }}
        itemProps={{ class: "hover:bg-neutral-800" }}
        contentProps={{ align: "start" }}
    />

    <div class="flex-1"></div>

    <div class="">
        <EntrySearchField service={service.entrySearch} />
    </div>
    
</div>
