// src/ui/modal/modal.svelte
<script lang="ts">
    import { ModalType } from "@/constants";
    import * as Dialog from "@/lib/components/dialog";

    import type { ModalProps } from "./modal-interface";
    import { EntryCreator } from "./entry-creator";
    import type { EntryCreatorService } from "./entry-creator";
    import { ProjectCreator } from "./project-creator";
    import type { ProjectCreatorService } from "./project-creator";

    const { service }: ModalProps = $props();
</script>

<Dialog.Dialog
    open={service.open}
    onOpenChange={(isOpen) => service.onOpenChange(isOpen)}
>
    {#if service.modalKey !== null && service.content}
        <Dialog.DialogContent class="sm:max-w-xl">
            <Dialog.DialogHeader>
                <Dialog.DialogTitle>{service.content.title}</Dialog.DialogTitle>
            </Dialog.DialogHeader>

            {#if service.modalKey === ModalType.ProjectCreator}
                <ProjectCreator
                    service={service.content as ProjectCreatorService}
                />
            {:else if service.modalKey === ModalType.EntryCreator}
                <EntryCreator
                    service={service.content as EntryCreatorService}
                />
            {/if}
        </Dialog.DialogContent>
    {/if}
</Dialog.Dialog>

// src/client/components/modal/modal.tsx
import { Modal as MantineModal } from "@mantine/core";
import { observer } from "mobx-react-lite";

import { ModalType } from "@/client/constants";

import { ProjectCreator, ProjectCreatorService } from "./project-creator";
import { EntryCreator, EntryCreatorService } from "./entry-creator";
import { ModalManager } from "./modal.service";

interface ModalManagerProps {
    service: ModalManager;
}

function renderModalContent({ service }: ModalManagerProps) {
    if (!service.modalKey) return null;

    if (service.modalKey == ModalType.ProjectCreator) {
        const contentService = service.content as ProjectCreatorService;
        return <ProjectCreator service={contentService} />;
    }

    if (service.modalKey == ModalType.EntryCreator) {
        const contentService = service.content as EntryCreatorService;
        return <EntryCreator service={contentService} />;
    }

    throw `Modal key ${service.modalKey} not recognized.`;
}

const ModalContent = observer(renderModalContent);

function renderModal({ service }: ModalManagerProps) {
    if (!service.modalKey || !service.content) return null;

    return (
        <MantineModal
            title={service.content.TITLE}
            opened={service.modalKey !== null}
            onClose={() => service.close()}
            portalProps={{ target: service.fetchPortalSelector.produceOne() }}
        >
            <ModalContent service={service} />
        </MantineModal>
    );
}

export const Modal = observer(renderModal);
