// src/components/center/entry-editor/entry-editor.tsx
import "./entry-editor.css";

import { Badge, Grid, Group, Space, Stack } from "@mantine/core";
import { observer } from "mobx-react-lite";

import { TableOfContents } from "@/components/lib/table-of-contents";
import { EntryViewType } from "@/constants";

import { ArticleEditor } from "./article-editor";
import { PropertyEditor } from "./property-editor";
import { WordEditor } from "./word-editor";
import { DeleteEntryButton } from "./buttons";
import { EntryEditorService } from "./entry-editor.service";

interface EntryEditorProps {
    service: EntryEditorService;
}

function renderEntryEditorHeader({ service }: EntryEditorProps) {
    return (
        <Group className="entry-editor-header">
            <Badge variant="outline" color="blue">
                {service.info.entryTypeLabel}
            </Badge>
            <div className="grow" />
            <DeleteEntryButton service={service} />
        </Group>
    );
}

const EntryEditorHeader = observer(renderEntryEditorHeader);

function renderEntryEditorContent({ service }: EntryEditorProps) {
    const viewKey = service.currentView;
    if (viewKey === EntryViewType.ArticleEditor)
        return <ArticleEditor service={service.article} />;
    if (viewKey === EntryViewType.PropertyEditor)
        return <PropertyEditor service={service.properties} />;
    if (viewKey === EntryViewType.WordEditor)
        return <WordEditor service={service.lexicon} />;
    return null;
}

const EntryEditorContent = observer(renderEntryEditorContent);

function renderEntryEditorTabs({ service }: EntryEditorProps) {
    return (
        <TableOfContents
            className="entry-editor-toc"
            data={service.tabData}
            activeValue={service.currentView}
            itemProps={{
                className: "entry-editor-toc-item",
                justify: "space-between",
            }}
        />
    );
}

export const EntryEditorTabs = observer(renderEntryEditorTabs);

function renderEntryEditor(props: EntryEditorProps) {
    return (
        <Stack className="entry-editor" gap={0}>
            <EntryEditorHeader {...props} />
            <Space className="entry-editor-space-below-header" />
            <Stack className="entry-editor-stack">
                <Grid className="entry-editor-grid">
                    <Grid.Col span={1}>
                        <EntryEditorTabs {...props} />
                    </Grid.Col>
                    <Grid.Col span={10}>
                        <EntryEditorContent {...props} />
                    </Grid.Col>
                </Grid>
            </Stack>
        </Stack>
    );
}

export const EntryEditor = observer(renderEntryEditor);

// src/ui/centre/entry-editor/entry-editor.svelte
<script lang="ts">
    import "./entry-editor.css";

    import { EntryViewType } from "@/constants";
    import * as Breadcrumb from "@/lib/components/breadcrumb";
    import { Pill } from "@/lib/components/pill";

    import type { EntryEditorProps } from "./entry-editor-interface";
    import { ArticleEditor } from "./article-editor";
    import { PropertyEditor } from "./property-editor";
    import { WordEditor } from "./word-editor";
    import { DeleteEntryButton } from "./delete-entry-button";

    let { service }: EntryEditorProps = $props();
</script>

<div class="entry-editor-root grid w-full h-full">
    <div class="entry-editor-header flex items-center justify-between pb-1">
        <!-- TODO: turn this into a dynamic toolbar that changes depending on what tab is visible -->
        <div>
            <Pill class="inline-block me-2" size="sm">
                {service.info.entryTypeLabel}
            </Pill>

            <Breadcrumb.Root class="inline-block">
                <Breadcrumb.List>
                    <Breadcrumb.Item>
                        {service.info.title}
                    </Breadcrumb.Item>
                    <Breadcrumb.Separator />
                    <Breadcrumb.Item>
                        {service.currentViewLabel}
                    </Breadcrumb.Item>
                </Breadcrumb.List>
            </Breadcrumb.Root>
        </div>

        <DeleteEntryButton {service} />
    </div>

    <div class="entry-editor-panel overflow-hidden px-6 pt-1">
        {#if service.currentView === EntryViewType.ArticleEditor}
            <ArticleEditor service={service.article} />
        {:else if service.currentView === EntryViewType.PropertyEditor}
            <PropertyEditor service={service.properties} />
        {:else if service.currentView === EntryViewType.WordEditor}
            <WordEditor service={service.lexicon} />
        {:else}
            {null}
        {/if}
    </div>
</div>
