// src/components/modal/entry-creator/entry-creator.tsx
import { Button, ComboboxItem, Container, Group, Space } from "@mantine/core";
import { observer } from "mobx-react-lite";

import { FILE_ENTITY_TYPES, ENTITY_TYPE_LABELS } from "@/constants";
import { SelectField } from "@/components/lib/select-field";
import { TextField } from "@/components/lib/text-field";
import { compareStrings } from "@/utils/string";

import { EntryCreatorService } from "./entry-creator.service";

const ENTITY_TYPE_DROPDOWN_DATA: ComboboxItem[] = FILE_ENTITY_TYPES.map(
    (entityType) => ({
        label: ENTITY_TYPE_LABELS[entityType],
        value: entityType.toString(),
    }),
).sort((a, b) => compareStrings(a.label, b.label));

interface EntryCreatorProps {
    service: EntryCreatorService;
}

function renderEntryCreator({ service }: EntryCreatorProps) {
    return (
        <Container size="xs">
            <form onSubmit={(event) => service.submit(event)}>
                <SelectField
                    label="Entity"
                    placeholder="Select an entity type"
                    data={ENTITY_TYPE_DROPDOWN_DATA}
                    getValue={() => service.entryType?.toString() ?? null}
                    onChange={(entityType) =>
                        (service.entryType = Number(entityType))
                    }
                    comboboxProps={{
                        portalProps: {
                            target: service.fetchPortalSelector.produce(),
                        },
                    }}
                />
                <Space h="xs" />
                <TextField
                    label={"Title"}
                    placeholder="Enter a unique title"
                    getValue={() => service.entryTitle}
                    getError={() =>
                        service.isTitleUnique ? null : "Duplicate title"
                    }
                    onChange={(event) =>
                        (service.entryTitle = event.currentTarget.value)
                    }
                />
                <Group justify="flex-end" mt="md">
                    <Button type="submit">Submit</Button>
                </Group>
            </form>
        </Container>
    );
}

export const EntryCreator = observer(renderEntryCreator);

// src/ui/modal/entry-creator/entry-creator.svelte
<script lang="ts">
    import { FILE_ENTITY_TYPES, ENTITY_TYPE_LABELS } from "@/constants";
    import { Button } from "@/lib/components/button";
    import * as Dialog from "@/lib/components/dialog";
    import { Input } from "@/lib/components/input";
    import { Label } from "@/lib/components/label";
    import * as Select from "@/lib/components/select";
    import { compareStrings } from "@/utils/string";

    import type { EntryCreatorProps } from "./entry-creator-interface";

    const { service }: EntryCreatorProps = $props();

    const entityTypeOptions = FILE_ENTITY_TYPES.map((entityType) => ({
        value: entityType,
        label: ENTITY_TYPE_LABELS[entityType],
    })).sort((a, b) => compareStrings(a.label, b.label));

    let entityTypeValue = $derived(service.entryType?.toString() ?? "");

    function onTitleInput(event: Event) {
        service.entryTitle = (event.currentTarget as HTMLInputElement).value;
    }

    function onEntityTypeChange(value: string) {
        service.entryType = value === "" ? null : Number(value);
    }

    async function onSubmit(event: Event) {
        event.preventDefault();
        await service.submit();
    }
</script>

<form class="grid gap-4" onsubmit={onSubmit}>
    <div class="grid gap-2">
        <Label for="entry-entity-type">Entity</Label>
        <Select.Root
            type="single"
            value={entityTypeValue}
            onValueChange={onEntityTypeChange}
        >
            <Select.Trigger id="entry-entity-type" class="w-full">
                {service.entryType
                    ? ENTITY_TYPE_LABELS[service.entryType]
                    : "Select an entity type"}
            </Select.Trigger>
            <Select.Content>
                {#each entityTypeOptions as option (option.value)}
                    <Select.Item
                        value={option.value.toString()}
                        label={option.label}
                    />
                {/each}
            </Select.Content>
        </Select.Root>
    </div>

    <div class="grid gap-2">
        <Label for="entry-title">Title</Label>
        <Input
            id="entry-title"
            placeholder="Enter a unique title"
            value={service.entryTitle}
            oninput={onTitleInput}
            severity={service.isTitleUnique ? "normal" : "error"}
        />
        {#if !service.isTitleUnique}
            <p class="text-destructive text-sm">Duplicate title</p>
        {/if}
    </div>

    <Dialog.DialogFooter>
        <Button type="submit">Submit</Button>
    </Dialog.DialogFooter>
</form>
