// src/ui/centre/entry-editor/property-editor/property-editor.svelte
<script lang="ts">
    import { EntryTitle } from "../title";
    import { PropertyTable } from "./property-table";
    import type { PropertyEditorProps } from "./property-editor-interface";

    const { service }: PropertyEditorProps = $props();
</script>

{#if service}
    <div class="flex flex-col overflow-hidden w-full h-full">
        <EntryTitle service={service?.info ?? null} />
        <div class="space-y-4">
            <PropertyTable service={service?.tableService ?? null} />
        </div>
    </div>
{/if}

// src/components/center/entry-editor/property-editor/property-editor.tsx
import { Container, Stack } from "@mantine/core";
import { observer } from "mobx-react-lite";

import { SPACE } from "@/components/lib/common";

import { PropertyEditorService } from "./property-editor.service";
import { PropertyTable } from "./property-table";
import { TitleField } from "../title-field";

interface PropertyEditorProps {
    service: PropertyEditorService;
}

function renderPropertyEditor({ service }: PropertyEditorProps) {
    return (
        <Container className="property-editor">
            <Stack
                className="property-editor-stack"
                justify="flex-start"
                gap={0}
            >
                <TitleField service={service.info} />
                {SPACE}
                <PropertyTable service={service} />
            </Stack>
        </Container>
    );
}

export const PropertyEditor = observer(renderPropertyEditor);
